name: Feature Request
description: Suggest a new feature or functionality
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Provide a clear and concise summary of the feature you're requesting.
      placeholder: "I would like to add..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented.
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Target User
      description: Who would primarily benefit from this feature?
      options:
        - End Users
        - Developers/Contributors
        - Administrators
        - All Users
    validations:
      required: true
